# -*- coding: utf-8 -*-
"""cofe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yy1rmNdEifw1T5Q-JFPzkEXJFMGfBOcJ
"""

import random
import pandas as pd
import matplotlib.pyplot as plt

# ===== CONFIGURACIÓN INICIAL =====
capital_inicial = float(input("💰 Ingresa tu capital inicial: "))
capital = capital_inicial
acciones = 0
precio_cafe = 10000
dia = 1

historial_precios = []
movimientos = []

noticias = [
    "🌧️ Lluvias afectan la cosecha",
    "☀️ Buen clima impulsa la producción",
    "📦 Aumento de exportaciones",
    "📉 Caída de la demanda internacional",
    "📈 Alta demanda en Europa",
    "🚢 Problemas logísticos en puertos"
]

print("\n☕ Simulador de Inversión en Café ☕")

while True:
    print(f"\n📅 Día {dia}")
    print(f"Precio del café: ${precio_cafe:.2f}")
    print(f"Capital disponible: ${capital:.2f}")
    print(f"Acciones en posesión: {acciones}")

    print("\nOpciones:")
    print("1. Comprar acciones")
    print("2. Vender acciones")
    print("3. Avanzar día")
    print("4. Finalizar simulación")

    opcion = input("Selecciona una opción: ")

    if opcion == "1":
        cantidad = int(input("Cantidad de acciones a comprar: "))
        costo = cantidad * precio_cafe
        if costo <= capital:
            capital -= costo
            acciones += cantidad
            movimientos.append([dia, "Compra", cantidad, precio_cafe, capital])
            print("✅ Compra exitosa")
        else:
            print("❌ Capital insuficiente")

    elif opcion == "2":
        cantidad = int(input("Cantidad de acciones a vender: "))
        if cantidad <= acciones:
            capital += cantidad * precio_cafe
            acciones -= cantidad
            movimientos.append([dia, "Venta", cantidad, precio_cafe, capital])
            print("✅ Venta exitosa")
        else:
            print("❌ No tienes suficientes acciones")

    elif opcion == "3":
        noticia = random.choice(noticias)
        cambio = random.uniform(-0.06, 0.06)
        precio_cafe += precio_cafe * cambio

        historial_precios.append(precio_cafe)
        movimientos.append([dia, "Mercado", "-", precio_cafe, capital])

        print("\n📰 Noticia del día:", noticia)
        dia += 1

    elif opcion == "4":
        valor_final = capital + acciones * precio_cafe

        print("\n📊 RESULTADOS FINALES")
        print(f"Capital inicial: ${capital_inicial:.2f}")
        print(f"Capital final: ${valor_final:.2f}")
        print(f"Ganancia/Pérdida: ${valor_final - capital_inicial:.2f}")

        # ===== TABLA =====
        df = pd.DataFrame(
            movimientos,
            columns=["Día", "Acción", "Cantidad", "Precio", "Capital restante"]
        )
        display(df)

        # ===== GRÁFICA =====
        plt.figure(figsize=(8,4))
        plt.plot(historial_precios, marker='o')
        plt.title("Evolución del precio del café")
        plt.xlabel("Días")
        plt.ylabel("Precio")
        plt.grid(True)
        plt.show()

        print("☕ Fin del simulador")
        break

    else:
        print("❌ Opción inválida")