# -*- coding: utf-8 -*-
"""cofe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yy1rmNdEifw1T5Q-JFPzkEXJFMGfBOcJ
"""

import streamlit as st
import random
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Simulador Café", layout="centered")

st.title("☕ Cofe Trade Pro")

# ===== ESTADO INICIAL =====
if "capital" not in st.session_state:
    st.session_state.capital = 0.0
    st.session_state.acciones = 0
    st.session_state.precio = 10000.0
    st.session_state.dia = 1
    st.session_state.historial = []
    st.session_state.movimientos = []

# ===== CAPITAL INICIAL =====
if st.session_state.capital == 0:
    capital_inicial = st.number_input(
        "💰 Ingresa tu capital inicial",
        min_value=0.0,
        step=100000.0
    )
    if st.button("Iniciar simulación"):
        st.session_state.capital = capital_inicial
        st.rerun()

else:
    st.subheader(f"📅 Día {st.session_state.dia}")
    st.metric("Precio del café", f"${st.session_state.precio:,.2f}")
    st.metric("Capital disponible", f"${st.session_state.capital:,.2f}")
    st.metric("Acciones", st.session_state.acciones)

    col1, col2 = st.columns(2)

    # ===== COMPRAR =====
    with col1:
        cantidad_compra = st.number_input("Comprar acciones", min_value=0, step=1)
        if st.button("📥 Comprar"):
            costo = cantidad_compra * st.session_state.precio
            if costo <= st.session_state.capital:
                st.session_state.capital -= costo
                st.session_state.acciones += cantidad_compra
                st.session_state.movimientos.append(
                    [st.session_state.dia, "Compra", cantidad_compra, st.session_state.precio]
                )
                st.success("Compra realizada")
            else:
                st.error("Capital insuficiente")

    # ===== VENDER =====
    with col2:
        cantidad_venta = st.number_input("Vender acciones", min_value=0, step=1)
        if st.button("📤 Vender"):
            if cantidad_venta <= st.session_state.acciones:
                st.session_state.capital += cantidad_venta * st.session_state.precio
                st.session_state.acciones -= cantidad_venta
                st.session_state.movimientos.append(
                    [st.session_state.dia, "Venta", cantidad_venta, st.session_state.precio]
                )
                st.success("Venta realizada")
            else:
                st.error("No tienes suficientes acciones")

    # ===== AVANZAR DÍA =====
    if st.button("⏭️ Avanzar día"):
        cambio = random.uniform(-0.06, 0.06)
        st.session_state.precio += st.session_state.precio * cambio
        st.session_state.historial.append(st.session_state.precio)
        st.session_state.dia += 1

    # ===== TABLA =====
    if st.session_state.movimientos:
        st.subheader("📋 Movimientos")
        df = pd.DataFrame(
            st.session_state.movimientos,
            columns=["Día", "Tipo", "Cantidad", "Precio"]
        )
        st.dataframe(df)

    # ===== GRÁFICA =====
    if st.session_state.historial:
        st.subheader("📈 Precio del café")
        fig, ax = plt.subplots()
        ax.plot(st.session_state.historial, marker="o")
        ax.set_xlabel("Días")
        ax.set_ylabel("Precio")
        st.pyplot(fig)
